### ISSUE TITLE
[V10] Not actually working with latest FVTT V10

### ISSUE THREAD

**Issue by mech-tools** [farling42/fvtt-revealed-notes-manager#1] opened 2022-08-27 10:42 UTC
Hello,

Seems that there was a lot of changes with FVTT 10 since latest release. This module won't throw an error, but won't work as intended either.

**Comment by farling42** [comment] 2022-08-27 10:53
Ah yes. They have changed the linkage to use @UUID instead of the older @Compendium and @JournalEntry.Regards,MartinOn 27 Aug 2022 11:42, DarKDinDoN ***@***.***> wrote:
Hello,
Seems that there was a lot of changes with FVTT 10 since latest release. This module won't throw an error, but won't work as intended either.

**Comment by farling42** [comment] 2022-08-30 09:55
The basic problem has been fixed in version 2.1.
However the correct display based on permissions has not been tested yet due to an error in Foundry V10.279 with regards to trying to change the permission of journal entries.

**Closed as completed by farling42** 2022-08-30 09:55 UTC

**Comment by farling42** [comment] 2022-09-01 16:06
Visibility now works on Foundry 10.283
